### ISSUE TITLE
Making the popup disappear more quickly

### ISSUE THREAD

**Issue by logixoul** [patrickiel/VolumeScroller#7]
I used to use another app ("Volume2"), which, however, is buggy on my PC. It does show a popup when changing volume (via the scrollwheel) but this popup disappears in like 200ms, which is great because I don't want it to stay there, occluding my content, making me wait.

Would be great to have your app's popup behave like that. I'm not saying you need a config option for the timeout duration, because I see that you like minimalism :) but maybe just hardcode a shorter timeout? Thanks!

**Comment by logixoul** [comment]
Ok, 10 minutes later, the timeout duration is now nice (about 1 second versus the old 5 seconds). Not sure how that happened.

On my first test (10 minutes ago), the popup was much wider and included some sort of (promotional?) video inside of it. Now this video is gone, which might explain the nicer timeout duration?

**Comment by patrickiel** [comment]
The popup is created and managed by the OS. The look of the popup depends on the content you are playing and the player you are using. Hope that helps 🙂

**Comment by logixoul** [comment]
Yep, it helps. It led me to the following solution from the net:





***For Chrome:Please copy the following into the Chrome address
bar:about://flagsSearch the option "Hardware Media Key Handling" and change
it to Disabled*

Thanks!
